import {
  REACT_APP_LOGIN,
  REACT_APP_KEYCHAIN_SERVICE,
  REACT_APP_PROFILE,
  REACT_APP_LOGOUT,
} from '@env';

export default {
  REACT_APP_LOGIN,
  REACT_APP_KEYCHAIN_SERVICE,
  REACT_APP_PROFILE,
  REACT_APP_LOGOUT,
};
