import {
  REACT_APP_LOGIN,
  REACT_APP_KEYCHAIN_SERVICE,
  REACT_APP_PROFILE,
  REACT_APP_LOGOUT,
  REACT_APP_GET_ASSET_BY_STATUS,
  REACT_APP_GET_ASSET_BY_LOCATION,
} from '@env';

export default {
  REACT_APP_LOGIN,
  REACT_APP_KEYCHAIN_SERVICE,
  REACT_APP_PROFILE,
  REACT_APP_LOGOUT,
  REACT_APP_GET_ASSET_BY_STATUS,
  REACT_APP_GET_ASSET_BY_LOCATION,
};
